config/routes.rb
CoolRSSJobApp::Application.routes.draw do

  get "jobs/result"
  get "jobs/sources"
  
  resources :jobs

  root :to => 'main#welcome'
  match '/main/welcome' => 'main#welcome'
  match '/jobs/index' => 'jobs#index'

end

app/models/job.rb
class Job < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  def result
    @jobs = Job.all

    respond_to do |format|
      format.html # sources.html.erb
      format.json { render json: @jobs }
    end
  end

  def sources
    @jobs = Job.all

    respond_to do |format|
      format.html # sources.html.erb
      format.json { render json: @jobs }
    end
  end
  
  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @jobs }
    end
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
    @job = Job.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @job }
    end
  end

  # GET /jobs/new
  # GET /jobs/new.json
  def new
    @job = Job.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @job }
    end
  end

  # GET /jobs/1/edit
  def edit
    @job = Job.find(params[:id])
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(params[:job])

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render json: @job, status: :created, location: @job }
      else
        format.html { render action: "new" }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /jobs/1
  # PUT /jobs/1.json
  def update
    @job = Job.find(params[:id])

    respond_to do |format|
      if @job.update_attributes(params[:job])
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job = Job.find(params[:id])
    @job.destroy

    respond_to do |format|
      format.html { redirect_to jobs_url }
      format.json { head :ok }
    end
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController

   def welcome
     @num_sources = Job.count
   end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/jobs/_form.html.erb
<%= form_for(@job) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :source %><br />
    <%= f.text_field :source %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<h1>Editing job</h1>

<%= render 'form' %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<h1>Listing jobs</h1>

<table>
  <tr>
    <th>Source</th>
    <th>Url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @jobs.each do |job| %>
  <tr>
    <td><%= job.source %></td>
    <td><%= job.url %></td>
    <td><%= link_to 'Show', job %></td>
    <td><%= link_to 'Edit', edit_job_path(job) %></td>
    <td><%= link_to 'Destroy', job, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Add a New Source', new_job_path %>	
<%= link_to 'Back to Main', root_path %>

app/views/jobs/new.html.erb
<h1>New job</h1>

<%= render 'form' %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/result.html.erb
<h1>Jobs#result</h1>

<% require 'rss/1.0' %>
<% require 'rss/2.0' %>
<% require 'open-uri' %>

<% source = request.query_parameters[:url] %> 
<% content = "" %>
<% open(source) do |s| content = s.read end %>
<% rss = RSS::Parser.parse(content, false) %>

<% html = "<h4><a href='#{rss.channel.link}'>#{rss.channel.title}</a></h4>" %>
<% html << "<ol>" %>


<% rss.items.each_with_index do |i, j| %>
    <% html << "<li><a href='#{i.link}' target='_blank'>#{i.title}</a><br/>" %>
    <% html << "</li>" %>
<% end %>

<% html << "</ol>" %>

<%= html.html_safe %>>

<%= link_to 'Back to Sources', '/jobs/sources'%> <BR />
<%= link_to 'Back to Main', root_path %>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Source:</b>
  <%= @job.source %>
</p>

<p>
  <b>Url:</b>
  <%= @job.url %>
</p>


<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/sources.html.erb
<h1>Listing jobs</h1>

<table>
  <tr>
    <th>Source</th>
  </tr>

<% @jobs.each do |job| %>
  <tr>
	<td><%= link_to job.source, '/jobs/result?url='+job.url %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Back to Main', root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CoolRSSJobApp</title>
  <% # stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
	<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
	<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/main/welcome.html.erb
<h1>Welcome to the Job Seeker Application</h1>
<p></p>
We currently have <%= @num_sources %> sources.
<br /> <br />
<%= link_to 'Search from Sources', '/jobs/sources' %> <BR />
<%= link_to 'Manage Sources', jobs_url %>